# Generated by Django 5.2 on 2025-04-27 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HRRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=100)),
                ('employee_id', models.CharField(max_length=50)),
                ('request_type', models.CharField(choices=[('salary', 'خطاب مفردات المرتب'), ('health_insurance', 'خطاب تأمين صحي'), ('social_insurance', 'خطاب تأمين اجتماعي'), ('vacation', 'طلب اجازة')], max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='vacation_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
